---
homebrew_brewfile_dest: "{{ ansible_user_dir }}/.Brewfile"
homebrew:
  brews: "{{ homebrew_brews }}"
  brews_with_options: "{{ homebrew_brews_with_options }}"
  casks: "{{ homebrew_casks }}"
  taps: "{{ homebrew_taps }}"

pacman:
  packages: "{{ pacman_packages }}"
