---
homebrew_brewfile_dest: "{{ ansible_user_dir }}/.Brewfile"
chunkwmrc_dest: "{{ ansible_user_dir }}/.chunkwmrc"
homebrew:
  url: https://raw.githubusercontent.com/Homebrew/install/master/install
  brews: "{{ homebrew_brews }}"
  brews_with_options: "{{ homebrew_brews_with_options }}"
  casks: "{{ homebrew_casks }}"
  taps: "{{ homebrew_taps }}"
pacman:
  packages: "{{ pacman_packages }}"
skhdrc_dest: "{{ ansible_user_dir }}/.skhdrc"
