---
- name: Synchronize configuration files and directories
  ansible.builtin.import_role:
    name: configs

- name: Install operating system packages
  ansible.builtin.import_role:
    name: packages

- name: Install dein plugin manager for vim and configure plugins
  ansible.builtin.import_role:
    name: dein
