---
- name: Run the equivalent of "pacman -Syu"
  pacman:
    update_cache: true
    upgrade: true
  become: true

- name: Install packages from manifest
  pacman:
    name: "{{ pacman['packages'] }}"
    state: latest  # noqa 403
  become: true
