---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  become_user: "{{ ansible_user_id }}"

- name: Install packages from manifest
  yum:
    name: "{{ yum['packages'] }}"
    state: latest
  become_user: "{{ ansible_user_id }}"
