---
- name: Install packages from manifest
  apt:
    name: "{{ apt['packages'] }}"
    state: latest # noqa 403
    update_cache: yes
  become: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
