---
- name: Ensure logfile path with correct ownership
  ansible.builtin.file:
    path: "{{ logfile }}"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    state: touch
    access_time: preserve
    modification_time: preserve
  become: true
