---
- name: Install homebrew dependencies
  homebrew:
    name: "{{ homebrew['brews'] }}"
    state: present

- name: Add ansible-pull launchd configuration to root LaunchAgents
  template:
    src: launchd.j2
    dest: "{{ ansible_user_dir }}/Library/LaunchAgents/com.{{ ansible_user_id | regex_replace('\\.', '') }}.dotfiles.plist"
  notify: start-launchd

- name: Create newsyslog rotation config for dotfiles.log
  template:
    src: newsyslog.j2
    dest: "/etc/newsyslog.d/com.{{ ansible_user_id | regex_replace('\\.', '') }}.dotfiles.conf"
  become: yes
