---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_focal
    image: geerlingguy/docker-ubuntu2004-ansible
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    groups:
      - group_red
      - group_dog
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  inventory:
    group_vars:
      group_red:
        config_files:
          - content: |
              RED
            dest: "{{ ansible_user_dir }}/color"
            mode: "0644"
      group_dog:
        config_files:
          - content: |
              DOG
            dest: "{{ ansible_user_dir }}/animal"
            mode: "0400"
  log: true
verifier:
  name: ansible
