---
- name: Verify
  hosts: all
  tasks:
    - name: Read test file
      slurp:
        src: "{{ ansible_user_dir }}/color"
      register: testfile
    - name: Assert test file content
      assert:
        that: (testfile.content | b64decode | trim) == "RED"
