---
- name: Read config file
  slurp:
    src: "{{ config.dest }}"
  register: config_slurp

- name: Assert config file content
  assert:
    that: (config_slurp.content | b64decode) == config.content

- name: Read config file mode
  stat:
    path: "{{ config.dest }}"
  register: config_stat

- name: Assert config file mode
  assert:
    that: config_stat.stat.mode == config.mode
