---
- name: Read test file
  slurp:
    src: "{{ testfile.dest }}"
  register: testfile_slurp

- name: Assert test file content
  assert:
    that: (testfile_slurp.content | b64decode) == testfile.content

- name: Read test file mode
  stat:
    path: "{{ testfile.dest }}"
  register: testfile_stat

- name: Assert test file mode
  assert:
    that: testfile_stat.stat.mode == testfile.mode
