---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-archlinux-latest
    image: archlinux:latest
    dockerfile: ../resources/Dockerfile.j2
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
    capabilities:
      - SYS_ADMIN
    groups:
      - aglorei
      - aglorei_Archlinux
      - aglorei_personal
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
  - name: molecule-ubuntu-focal
    image: ubuntu:20.04
    dockerfile: ../resources/Dockerfile.j2
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: sudo
      DEPLOY_GROUP: deployer
    capabilities:
      - SYS_ADMIN
    groups:
      - aglorei
      - aglorei_Ubuntu
      - aglorei_work_1
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  inventory:
    host_vars:
      molecule-archlinux-latest:
        ansible_user: ansible
      molecule-ubuntu-focal:
        ansible_user: ansible
  log: true
  playbooks:
    prepare: resources/prepare.yml
verifier:
  name: ansible
