---
- name: Verify
  hosts: all
  tasks:
    - name: Assert dein installation
      include_tasks: resources/verify_dein.yml
    - name: Assert packages installation
      include_tasks: resources/verify_packages.yml
