---
- name: Verify
  hosts: all
  tasks:
    - name: Assert dein plugin installation
      include_tasks: resources/verify_directories.yml
      loop: "{{ dein_plugins_repos }}"
      loop_control:
        loop_var: config
    - name: Assert packages installation
      include_tasks: resources/verify_packages.yml
