---
- name: Check vim base directory
  ansible.builtin.stat:
    path: "{{ dein_bundles_dir }}"
  register: dircheck

- name: Install dein plugin manager
  block:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: temp_dir
    - name: Download dein installer
      ansible.builtin.get_url:
        url: "{{ dein_url }}"
        dest: "{{ temp_dir.path }}"
    - name: Execute dein installer
      ansible.builtin.command: "sh {{ temp_dir.path }}/installer.sh {{ dein_bundles_dir }}"
      register: dein_installer
    - name: Install dein plugins
      ansible.builtin.command: "nvim +\"call dein#install()\" +qall"
      register: dein_installer
  always:
    - name: Cleanup temporary build directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
  when: not dircheck.stat.exists
