---
- name: Check vim base directory
  stat:
    path: "{{ dein_bundles_dir }}"
  register: dircheck

- name: Install dein plugin manager
  block:
    - name: Create temporary build directory
      tempfile:
        state: directory
        suffix: build
      register: temp_dir

    - name: Download dein installer
      get_url:
        url: "{{ dein_url }}"
        dest: "{{ temp_dir.path }}"

    - name: Execute dein installer
      command: "sh {{ temp_dir.path }}/installer.sh {{ dein_bundles_dir }}"
      register: dein_installer
  always:
    - name: Cleanup temporary build directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent
  when: not dircheck.stat.exists
