---
os_packages:
  apt:
    - ansible
    - apache2-utils
    - arp-scan
    - awscli
    - certbot
    - cmake
    - docker
    - dnsutils
    - fasd
    - fd-find
    - fzf
    - gist
    - git
    - gnuplot
    # - grub-pc
    - htop
    - jq
    - lastpass-cli
    - lsof
    - maven
    - neofetch
    - neovim
    - netdata
    - nmap
    - p7zip
    - packer
    - pipenv
    - postgresql
    - python3
    - python3-msgpack
    - python3-pynvim
    - ripgrep
    - rsync
    - strongswan
    - tmux
    - traceroute
    - transmission-cli
    - tree
    - unzip
    - vim
    - wget
    - whois
    - wireshark
    - zsh
