---
os_packages:
  apt:
    - ansible
    - apache2-utils
    - arp-scan
    - awscli
    - certbot
    - cmake
    - docker
    - dnsutils
    - fasd
    - fd-find
    - fzf
    - git
    - gnuplot
    - grub-pc
    - htop
    - jq
    - lastpass-cli
    - lsof
    - maven
    - neofetch
    - neovim
    - netdata
    - nmap
    - nodejs
    - p7zip
    - packer
    - pipenv
    - postgresql
    - python3
    - python3-msgpack
    - python3-pynvim
    - ripgrep
    - rsync
    - strongswan
    - tmux
    - traceroute
    - tree
    - unzip
    - vim
    - wget
    - whois
    - wireshark
    - zsh
  homebrew:
    - ansible
    - arp-scan
    - awscli
    - azure-cli
    - cmake
    - colima
    - cowsay
    - docker
    - doctl
    - fasd
    - fd
    - figlet
    - fortune
    - fzf
    - git
    - gnupg
    - helm
    - htop
    - ifstat
    - jq
    - koekeishiya/formulae/yabai
    - kubernetes-cli
    - lastpass-cli
    - minikube
    - neofetch
    - neovim
    - netdata
    - nmap
    - node
    - openjdk
    - p7zip
    - packer
    - pipenv
    - pipes-sh
    - pstree
    - ripgrep
    - telnet
    - terraform
    - tmux
    - tree
    - tty-clock
    - vim
    - wget
    - wireshark
    - zsh
  homebrew_with_options:
    koekeishiya/formulae/skhd:
      - HEAD
  homebrew_casks:
    - barrier
    - brave-browser
    - font-mononoki
    - iterm2
    - microsoft-office
    - microsoft-teams
    - miro
    - slack
    - zoom
  homebrew_taps:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-drivers
    - homebrew/cask-fonts
    - homebrew/cask-versions
    - homebrew/core
    - homebrew/services
    - koekeishiya/formulae
  pacman:
    # groups
    - base
    # pacman -Sg base-devel
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - file
    - findutils
    - flex
    - gawk
    - gcc
    - gettext
    - grep
    - groff
    - gzip
    - libtool
    - m4
    - make
    - pacman
    - patch
    - pkgconf
    - sed
    - sudo
    - texinfo
    - which
    # individual
    - ansible
    - apache
    - arp-scan
    - aws-cli
    - bind
    - certbot
    - cmake
    - cronie
    - docker
    - fasd
    - fd
    - fzf
    - git
    - gnuplot
    - grub
    - htop
    - jq
    - keybase
    - kubectl
    - lastpass-cli
    - lsof
    - maven
    - neofetch
    - neovim
    - netdata
    - nmap
    - nodejs
    - npm
    - openssh
    - p7zip
    - packer
    - postgresql
    - python
    - python-pipenv
    - python-pynvim
    - ripgrep
    - rsync
    - strongswan
    - terraform
    - tmux
    - traceroute
    - tree
    - unzip
    - vim
    - wget
    - whois
    - wireshark-cli
    - zsh

vaulted_files: "{{ vault_vaulted_files }}"
