---
- name: Prepare
  hosts: all
  tasks:
    - name: Install Archlinux requisite packages
      community.general.pacman:
        name:
          - git
          - rsync
        state: present
        update_cache: true
      become: true
      when: ansible_distribution == "Archlinux"
    - name: Install Ubuntu requisite packages
      ansible.builtin.apt:
        name:
          - git
          - rsync
        state: present
        update_cache: true
      become: true
      when: ansible_distribution == "Ubuntu"
