---
- name: Read directory mode
  stat:
    path: "{{ config.dest | dirname }}"
  register: configdir_stat
  when: config.dir_mode is defined

- name: Assert directory mode
  assert:
    that: configdir_stat.stat.mode == config.dir_mode
  when: config.dir_mode is defined

- name: Read file
  slurp:
    src: "{{ config.dest }}"
  register: config_slurp

- name: Assert file content
  assert:
    that: (config_slurp.content | b64decode) == config.content

- name: Read file mode
  stat:
    path: "{{ config.dest }}"
  register: config_stat

- name: Assert file mode
  assert:
    that: config_stat.stat.mode == config.mode
