---
- name: Verify
  hosts: all
  tasks:
    - name: Assert configuration file copies
      include_tasks: verify_files.yml
      loop: "{{ config_files }}"
      loop_control:
        loop_var: config
    - name: Assert configuration directory synchronization
      include_tasks: verify_directories.yml
      loop: "{{ config_dirs }}"
      loop_control:
        loop_var: config
    - name: Assert dein plugin installation
      include_tasks: verify_directories.yml
      loop: "{{ dein_plugins }}"
      loop_control:
        loop_var: config
    - name: Assert packages installation
      include_tasks: verify_packages.yml
