---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Assert package
  ansible.builtin.assert:
    that: package in ansible_facts.packages
  loop: "{{ os_packages[ansible_facts.pkg_mgr] }}"
  loop_control:
    loop_var: package
