---
- name: Verify
  hosts: all
  tasks:
    - name: Read plugin repositories
      ansible.builtin.find:
        depth: 2
        file_type: directory
        paths: "{{ dein_plugins_dir }}"
        recurse: true
      register: dein_repos_find

    - name: Assert plugins directories
      ansible.builtin.assert:
        that: repo in (dein_repos_find.files | map(attribute='path'))
      loop: "{{ dein_plugins_repos }}"
      loop_control:
        loop_var: repo

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert package
      ansible.builtin.assert:
        that: package in ansible_facts.packages
      loop: "{{ os_packages[ansible_facts.pkg_mgr] }}"
      loop_control:
        loop_var: package
