---
config_dirs:
  - src: >-
      {{ inventory_hostname }}/base16-shell
    dest: >-
      {{ ansible_user_dir }}/.config/base16-shell
  - src: >-
      {{ inventory_hostname }}/zsh-syntax-highlighting
    dest: >-
      {{ ansible_user_dir }}/.zsh
  - src: >-
      {{ inventory_hostname }}/geometry
    dest: >-
      {{ ansible_user_dir }}/.geometry
  - src: >-
      {{ inventory_hostname }}/oh-my-zsh
    dest: >-
      {{ ansible_user_dir }}/.oh-my-zsh

config_files: >-
  {{ distribution_files + unix_files + vaulted_files }}

unix_files:
  - content: >-
      {{ lookup('template', inventory_hostname + '/.gitconfig') }}
    dest: >-
      {{ ansible_user_dir }}/.gitconfig
    mode: "0644"
  - content: >-
      {{ lookup('template', inventory_hostname + '/.gitignore_global') }}
    dest: >-
      {{ ansible_user_dir }}/.gitignore_global
    mode: "0644"
  - content: >-
      {{ lookup('template', inventory_hostname + '/.tmux.conf') }}
    dest: >-
      {{ ansible_user_dir }}/.tmux.conf
    mode: "0644"
  - content: >-
      {{ lookup('template', inventory_hostname + '/.vimrc') }}
    dest: >-
      {{ ansible_user_dir }}/.vimrc
    mode: "0644"
  - content: >-
      {{ lookup('template', inventory_hostname + '/.zshrc') }}
    dest: >-
      {{ ansible_user_dir }}/.zshrc
    mode: "0644"
  - content: >-
      {{ lookup('template', inventory_hostname + '/gpg-agent.conf') }}
    dest: >-
      {{ ansible_user_dir }}/.gnupg/gpg-agent.conf
    mode: "0644"
    dir_mode: "0700"
  - content: >-
      {{ lookup('template', inventory_hostname + '/htoprc') }}
    dest: >-
      {{ ansible_user_dir }}/.config/htop/htoprc
    mode: "0644"
    dir_mode: "0700"
  - content: >-
      {{ lookup('template', inventory_hostname + '/init.vim') }}
    dest: >-
      {{ ansible_user_dir }}/.config/nvim/init.vim
    mode: "0644"
    dir_mode: "0700"

dein_bundles_dir: "{{ ansible_user_dir }}/.vim/bundles"
dein_plugins_dir: "{{ dein_bundles_dir }}/repos/github.com"
# TODO: Implement better init.vim templating
dein_plugins_repos:
  - "{{ dein_plugins_dir }}/Shougo/dein.vim"
  - "{{ dein_plugins_dir }}/vim-airline/vim-airline"
  - "{{ dein_plugins_dir }}/vim-airline/vim-airline-themes"
  - "{{ dein_plugins_dir }}/chriskempson/base16-vim"
  - "{{ dein_plugins_dir }}/Raimondi/delimitMate"
  - "{{ dein_plugins_dir }}/tpope/vim-commentary"
  - "{{ dein_plugins_dir }}/tpope/vim-surround"
  - "{{ dein_plugins_dir }}/ctrlpvim/ctrlp.vim"
  - "{{ dein_plugins_dir }}/scrooloose/syntastic"
  - "{{ dein_plugins_dir }}/PProvost/vim-ps1"
  - "{{ dein_plugins_dir }}/neoclide/coc.nvim"
  - "{{ dein_plugins_dir }}/airblade/vim-gitgutter"

git:
  core:
    editor: nvim
  # set all vaulted variables in subgroups
  user: "{{ vault_git_user }}"

os_packages:
  apt:
    - ansible
    - apache2-utils
    - arp-scan
    - awscli
    - certbot
    - cmake
    - docker
    - dnsutils
    - fasd
    - fd-find
    - fzf
    - git
    - gnuplot
    - grub-pc
    - htop
    - jq
    - lastpass-cli
    - lsof
    - maven
    - neofetch
    - neovim
    - netdata
    - nmap
    - nodejs
    - p7zip
    - packer
    - pipenv
    - postgresql
    - python3
    - python3-msgpack
    - python3-pynvim
    - ripgrep
    - rsync
    - strongswan
    - tmux
    - traceroute
    - transmission-cli
    - tree
    - unzip
    - vim
    - wget
    - whois
    - wireshark
    - zsh
  homebrew:
    - ansible
    - arp-scan
    - awscli
    - azure-cli
    - cmake
    - cowsay
    - koekeishiya/formulae/yabai
    - doctl
    - fasd
    - fd
    - figlet
    - fortune
    - fzf
    - git
    - gnupg
    - helm
    - htop
    - ifstat
    - jq
    - kubernetes-cli
    - lastpass-cli
    - neofetch
    - neovim
    - netdata
    - nmap
    - node
    - p7zip
    - packer
    - pipenv
    - pipes-sh
    - pstree
    - ripgrep
    - telnet
    - terraform
    - tmux
    - transmission-cli
    - tree
    - tty-clock
    - vim
    - wget
    - wireshark
    - zsh
  homebrew_with_options:
    koekeishiya/formulae/skhd:
      - with-logging
  homebrew_casks:
    - alfred
    - authy
    - barrier
    - brave-browser
    - docker
    - font-mononoki-nerd-font-mono
    - iterm2
    - java
    - keybase
    - mactex
    - minikube
    - miro
    - rocket
    - signal
    - slack
    - spotify
    - steam
    - vlc
  homebrew_taps:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-drivers
    - homebrew/cask-fonts
    - homebrew/cask-versions
    - homebrew/core
    - homebrew/services
    - koekeishiya/formulae
  pacman:
    # groups
    - base
    # pacman -Sg base-devel
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - file
    - findutils
    - flex
    - gawk
    - gcc
    - gettext
    - grep
    - groff
    - gzip
    - libtool
    - m4
    - make
    - pacman
    - patch
    - pkgconf
    - sed
    - sudo
    - texinfo
    - which
    # individual
    - ansible
    - apache
    - arp-scan
    - aws-cli
    - bind
    - certbot
    - cmake
    - cronie
    - docker
    - fasd
    - fd
    - fzf
    - git
    - gnuplot
    - grub
    - htop
    - jq
    - keybase
    - kubectl
    - lastpass-cli
    - lsof
    - maven
    - neofetch
    - neovim
    - netdata
    - nmap
    - nodejs
    - npm
    - openssh
    - p7zip
    - packer
    - postgresql
    - python
    - python-pipenv
    - python-pynvim
    - ripgrep
    - rsync
    - strongswan
    - terraform
    - tmux
    - traceroute
    - transmission-cli
    - tree
    - unzip
    - vim
    - wget
    - whois
    - wireshark-cli
    - zsh

pinentry_path:
  Archlinux: /usr/bin/pinentry-curses
  MacOSX: /usr/local/bin/pinentry-curses
  RedHat: /usr/bin/pinentry-curses
  Ubuntu: /usr/bin/pinentry-curses
