---
git_core:
  editor: nvim
homebrew_brews:
  - ansible
  - arp-scan
  - awscli
  - azure-cli
  - cmake
  - cowsay
  - koekeishiya/formulae/chunkwm
  - doctl
  - fasd
  - fd
  - figlet
  - fortune
  - fzf
  - gist
  - git
  - gnupg
  - helm
  - htop
  - ifstat
  - jq
  - kubernetes-cli
  - lastpass-cli
  - neofetch
  - neovim
  - netdata
  - nmap
  - node
  - p7zip
  - packer
  - pipenv
  - pipes-sh
  - pstree
  - python@2
  - ripgrep
  - telnet
  - terraform
  - tmux
  - transmission-cli
  - tree
  - tty-clock
  - vim
  - wget
  - wireshark
  - zsh
homebrew_brews_with_options:
  koekeishiya/formulae/skhd:
    - with-logging
homebrew_casks:
  - alfred
  - authy
  - brave-browser-beta
  - docker
  - firefox-beta
  - font-mononoki-nerd-font-mono
  - iterm2-beta
  - java
  - keybase
  - mactex
  - minikube
  - rocket
  - signal
  - slack-beta
  - spotify
  - steam
  - vlc
homebrew_taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - koekeishiya/formulae
pacman_packages:
  # groups
  - base
  - base-devel
  # individual
  - ansible
  - apache
  - arp-scan
  - aws-cli
  - bind-tools
  - certbot
  - cmake
  - cronie
  - docker
  - fasd
  - fd
  - fzf
  - gist
  - git
  - gnuplot
  - grub
  - htop
  - jq
  - keybase
  - kubectl
  - lastpass-cli
  - lsof
  - maven
  - neofetch
  - neovim
  - netdata
  - nmap
  - openssh
  - p7zip
  - packer
  - postgresql
  - python
  - python-pipenv
  - python-pynvim
  - ripgrep
  - rsync
  - strongswan
  - terraform
  - tmux
  - traceroute
  - transmission-cli
  - tree
  - unzip
  - vim
  - wget
  - whois
  - wireshark-cli
  - zsh
