---
pacman_packages:
  - tmux
  - vim
homebrew_brews:
  - vim
homebrew_brews_with_options:
  tmux:
    - HEAD
homebrew_casks:
  - alfred
homebrew_taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/core
  - homebrew/services
