---
- name: Synchronize util directories
  synchronize:
    src: "{{ config['src'] }}/"
    dest: "{{ config['dest'] }}/"
    checksum: yes
    recursive: yes
    times: no
  loop: "{{ util_config_directories }}"
  loop_control:
    loop_var: config
