---
- name: Prepare
  hosts: all
  tasks:
    - name: Prepare Archlinux instances
      block:
        - name: Install requisite packages
          pacman:
            name:
              - git
              - rsync
            state: present
            update_cache: true
      when: ansible_distribution == "Archlinux"
    - name: Prepare Ubuntu instances
      block:
        - name: Install requisite packages
          apt:
            name:
              - git
              - rsync
            state: present
            update_cache: true
      when: ansible_distribution == "Ubuntu"
