---
galaxy_info:
  author: aglorei
  description: Set up dotfiles playlist as an ansible-pull cron
  license: MIT
  min_ansible_version: 2.10.3
  platforms:
    - name: Archlinux
      versions:
        - any
    - name: MacOSX
      versions:
        - 10.15
    - name: Ubuntu
      versions:
        - focal

allow_duplicates: false
dependencies:
  - role: packages
    vars:
      os_packages:
        apt:
          - neovim
        homebrew:
          - neovim
        pacman:
          - neovim
