---
galaxy_info:
  author: aglorei
  description: Set up dotfiles playlist as an ansible-pull cron
  license: MIT
  min_ansible_version: 2.10.4
  platforms:
    - name: Archlinux
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - 20.04

dependencies:
  - role: packages
    vars:
      homebrew_brews:
        - ansible
      pacman_packages:
        - ansible
        - cronie
    notify: start-cronie

  - role: common
    vars:
      config_files:
        - content: "{{ lookup('template', 'logrotate.j2') }}"
          dest: "/etc/logrotate.d/dotfiles"
          mode: "0644"
          dir_mode: "0755"
      config_dirs: []
    become: yes
    when: ansible_distribution == "Archlinux"

  - role: common
    vars:
      config_files:
        - content: "{{ lookup('template', 'launchd.j2') }}"
          dest: "{{ launch_agent_dir }}/com.{{ ansible_user_id_safe }}.dotfiles.plist"
          mode: "0644"
          dir_mode: "0755"
      config_dirs: []
    notify: start-launchd
    when: ansible_distribution == "MacOSX"

  - role: common
    vars:
      config_files:
        - content: "{{ lookup('template', 'newsyslog.j2') }}"
          dest: "{{ newsyslog_dir }}/com.{{ ansible_user_id_safe }}.dotfiles.conf"
          mode: "0644"
          dir_mode: "0755"
      config_dirs: []
    become: yes
    when: ansible_distribution == "MacOSX"
