---
galaxy_info:
  author: aglorei
  description: Set up dotfiles playbook as an ansible-pull cron
  license: MIT
  min_ansible_version: 2.10.3
  platforms:
    - name: Archlinux
      versions:
        - any
    - name: MacOSX
      versions:
        - 10.15

allow_duplicates: false
dependencies:
  - role: packages
    vars:
      os_packages:
        homebrew:
          - ansible
        pacman:
          - ansible
          - cronie
    notify: start-cronie
  - role: configs
    vars:
      config_files:
        - content: "{{ lookup('template', 'logrotate.j2') }}"
          dest: "/etc/logrotate.d/dotfiles"
          mode: "0644"
          dir_mode: "0755"
      config_dirs: []
    become: true
    when: ansible_distribution == "Archlinux"
  - role: configs
    vars:
      config_files:
        - content: "{{ lookup('template', 'launchd.j2') }}"
          dest: "{{ launch_agent_dir }}/com.dotfiles.plist"
          mode: "0644"
          dir_mode: "0755"
      config_dirs: []
    notify: start-launchd
    when: ansible_distribution == "MacOSX"
  - role: configs
    vars:
      config_files:
        - content: "{{ lookup('template', 'newsyslog.j2') }}"
          dest: "{{ newsyslog_dir }}/com.dotfiles.conf"
          mode: "0644"
          dir_mode: "0755"
      config_dirs: []
    become: true
    when: ansible_distribution == "MacOSX"
