---
- name: start-cronie
  ansible.builtin.systemd:
    name: cronie
    enabled: true
    state: started
  become: true

- name: start-launchd
  community.general.launchd:
    name: "com.{{ ansible_user_id | regex_replace('\\.', '') }}.dotfiles"
    state: started
