---
- name: Verify
  hosts: all
  tasks:
    - name: Assert file copies and directory synchronization
      include_tasks: verify_configs.yml
      loop: "{{ config_files }}"
      loop_control:
        loop_var: config
