---
distribution_files:
  - content: "{{ lookup('template', inventory_hostname + '/.Brewfile') }}"
    dest: "{{ ansible_user_dir }}/.Brewfile"
    mode: "0644"
  - content: "{{ lookup('template', inventory_hostname + '/.yabairc') }}"
    dest: "{{ ansible_user_dir }}/.yabairc"
    mode: "0755"
  - content: "{{ lookup('template', inventory_hostname + '/.skhdrc') }}"
    dest: "{{ ansible_user_dir }}/.skhdrc"
    mode: "0644"

ansible_user_id_safe: "{{ ansible_user_id | regex_replace('\\.', '') }}"
launch_agent_dir: "{{ ansible_user_dir }}/Library/LaunchAgents"
newsyslog_dir: /etc/newsyslog.d
