---
config_dirs:
  - src: >-
      molecule_group_1/sync1
    dest: >-
      {{ ansible_user_dir }}/sync1
  - src: >-
      molecule_group_1/sync2
    dest: >-
      {{ ansible_user_dir }}/sync2
  - src: >-
      molecule_group_1/sync3
    dest: >-
      {{ ansible_user_dir }}/sync3

config_files:
  - content: |
      TEST CONTENT A
    dest: "{{ ansible_user_dir }}/a"
    mode: "0400"
  - content: |
      TEST CONTENT B
    dest: "{{ ansible_user_dir }}/1/b"
    mode: "0644"
    dir_mode: "0700"
  - content: |
      TEST CONTENT C
    dest: "{{ ansible_user_dir }}/1/2/c"
    mode: "0644"
    dir_mode: "0755"

dein_bundles_dir: "{{ ansible_user_dir }}/.vim/bundles"
