---
name: build

on: [push, pull_request]

jobs:
  ansible-lint:
    name: Lint Ansible project
    runs-on: ubuntu-latest
    steps:
      - name: Lint Ansible project
        uses: ansible/ansible-lint-action@v4
        with:
          override-deps: |
            ansible==2.10.4
            ansible-lint==4.3.7
          targets: "./"
